const data = {
  results: [
    {
      PACKAGING: "PET-EW",
      KEY_ACCOUNT_SPEC: "Adeg SM",
      PRICE: "0.99",
      PRODUCT_NAME: "Coca-Cola Original",
      BRAND: "Coca-Cola",
    },
    {
      PACKAGING: "PET-EW",
      KEY_ACCOUNT_SPEC: "Adeg SM",
      PRICE: "0.99",
      PRODUCT_NAME: "Coca-Cola Light",
      BRAND: "Coca-Cola Light",
    },
    {
      PACKAGING: "PET-EW",
      KEY_ACCOUNT_SPEC: "Adeg SM",
      PRICE: "0.99",
      PRODUCT_NAME: "Coca-Cola Zero",
      BRAND: "Coca-Cola Zero",
    },
    {
      PACKAGING: "PET-EW",
      KEY_ACCOUNT_SPEC: "Adeg SM",
      PRICE: "0.99",
      PRODUCT_NAME: "Coca-Cola Zero Lemon",
      BRAND: "Coca-Cola Zero",
    },
    {
      PACKAGING: "PET-EW",
      KEY_ACCOUNT_SPEC: "Adeg SM",
      PRICE: "0.99",
      PRODUCT_NAME: "Fanta Original Orange",
      BRAND: "Fanta",
    },
    {
      PACKAGING: "PET-EW",
      KEY_ACCOUNT_SPEC: "AFS",
      PRICE: "1.99",
      PRODUCT_NAME: "Coca-Cola Original",
      BRAND: "Coca-Cola",
    },
    {
      PACKAGING: "PET-EW",
      KEY_ACCOUNT_SPEC: "AFS",
      PRICE: "1.99",
      PRODUCT_NAME: "Fanta Original Orange",
      BRAND: "Fanta",
    },
    {
      PACKAGING: "Glas-Flasche Mehrweg",
      KEY_ACCOUNT_SPEC: "AGM Gastro C+C",
      PRICE: "0.51",
      PRODUCT_NAME: "Coca-Cola Original",
      BRAND: "Coca-Cola",
    },
    {
      PACKAGING: "PET-EW",
      KEY_ACCOUNT_SPEC: "AGM Gastro C+C",
      PRICE: "0.70",
      PRODUCT_NAME: "Coca-Cola Original",
      BRAND: "Coca-Cola",
    },
    {
      PACKAGING: "PET-EW",
      KEY_ACCOUNT_SPEC: "AGM Gastro C+C",
      PRICE: "1.39",
      PRODUCT_NAME: "Coca-Cola Original",
      BRAND: "Coca-Cola",
    },
    {
      PACKAGING: "Glas-Flasche Mehrweg",
      KEY_ACCOUNT_SPEC: "AGM Gastro C+C",
      PRICE: "0.51",
      PRODUCT_NAME: "Coca-Cola Light",
      BRAND: "Coca-Cola Light",
    },
    {
      PACKAGING: "Glas-Flasche Mehrweg",
      KEY_ACCOUNT_SPEC: "AGM Gastro C+C",
      PRICE: "0.51",
      PRODUCT_NAME: "Coca-Cola Zero",
      BRAND: "Coca-Cola Zero",
    },
    {
      PACKAGING: "PET-EW",
      KEY_ACCOUNT_SPEC: "AGM Gastro C+C",
      PRICE: "0.70",
      PRODUCT_NAME: "Fanta Original Orange",
      BRAND: "Fanta",
    },
    {
      PACKAGING: "PET-EW",
      KEY_ACCOUNT_SPEC: "AGM Gastro C+C",
      PRICE: "1.39",
      PRODUCT_NAME: "Fanta Original Orange",
      BRAND: "Fanta",
    },
    {
      PACKAGING: "PET-EW",
      KEY_ACCOUNT_SPEC: "Berger & Wedl C+C",
      PRICE: "1.35",
      PRODUCT_NAME: "Coca-Cola Original",
      BRAND: "Coca-Cola",
    },
    {
      PACKAGING: "PET-EW",
      KEY_ACCOUNT_SPEC: "Berger & Wedl C+C",
      PRICE: "1.65",
      PRODUCT_NAME: "Coca-Cola Original",
      BRAND: "Coca-Cola",
    },
    {
      PACKAGING: "PET-EW",
      KEY_ACCOUNT_SPEC: "Berger & Wedl C+C",
      PRICE: "1.35",
      PRODUCT_NAME: "Coca-Cola Light",
      BRAND: "Coca-Cola Light",
    },
    {
      PACKAGING: "PET-EW",
      KEY_ACCOUNT_SPEC: "Berger & Wedl C+C",
      PRICE: "1.65",
      PRODUCT_NAME: "Coca-Cola Light",
      BRAND: "Coca-Cola Light",
    },
    {
      PACKAGING: "PET-EW",
      KEY_ACCOUNT_SPEC: "Berger & Wedl C+C",
      PRICE: "1.35",
      PRODUCT_NAME: "Coca-Cola Zero",
      BRAND: "Coca-Cola Zero",
    },
    {
      PACKAGING: "PET-EW",
      KEY_ACCOUNT_SPEC: "Berger & Wedl C+C",
      PRICE: "1.35",
      PRODUCT_NAME: "Fanta Original Orange",
      BRAND: "Fanta",
    },
    {
      PACKAGING: "PET-EW",
      KEY_ACCOUNT_SPEC: "Berger & Wedl C+C",
      PRICE: "1.65",
      PRODUCT_NAME: "Fanta Original Orange",
      BRAND: "Fanta",
    },
    {
      PACKAGING: "PET-EW",
      KEY_ACCOUNT_SPEC: "Billa",
      PRICE: "0.94",
      PRODUCT_NAME: "Coca-Cola Original",
      BRAND: "Coca-Cola",
    },
    {
      PACKAGING: "PET-EW",
      KEY_ACCOUNT_SPEC: "Billa",
      PRICE: "0.94",
      PRODUCT_NAME: "Coca-Cola Zero",
      BRAND: "Coca-Cola Zero",
    },
    {
      PACKAGING: "PET-EW",
      KEY_ACCOUNT_SPEC: "Billa",
      PRICE: "0.94",
      PRODUCT_NAME: "Coca-Cola Zero Lemon",
      BRAND: "Coca-Cola Zero",
    },
    {
      PACKAGING: "PET-EW",
      KEY_ACCOUNT_SPEC: "Billa",
      PRICE: "0.94",
      PRODUCT_NAME: "Fanta Original Orange",
      BRAND: "Fanta",
    },
    {
      PACKAGING: "PET-EW",
      KEY_ACCOUNT_SPEC: "Billa Plus",
      PRICE: "0.94",
      PRODUCT_NAME: "Coca-Cola Original",
      BRAND: "Coca-Cola",
    },
    {
      PACKAGING: "Dose EW",
      KEY_ACCOUNT_SPEC: "Billa Plus",
      PRICE: "0.79",
      PRODUCT_NAME: "Coca-Cola Vanilla",
      BRAND: "Coca-Cola",
    },
    {
      PACKAGING: "PET-EW",
      KEY_ACCOUNT_SPEC: "Billa Plus",
      PRICE: "0.94",
      PRODUCT_NAME: "Coca-Cola Zero",
      BRAND: "Coca-Cola Zero",
    },
    {
      PACKAGING: "Dose EW",
      KEY_ACCOUNT_SPEC: "Billa Plus",
      PRICE: "0.79",
      PRODUCT_NAME: "Coca-Cola Zero Lemon",
      BRAND: "Coca-Cola Zero",
    },
    {
      PACKAGING: "PET-EW",
      KEY_ACCOUNT_SPEC: "Billa Plus",
      PRICE: "0.94",
      PRODUCT_NAME: "Coca-Cola Zero Lemon",
      BRAND: "Coca-Cola Zero",
    },
    {
      PACKAGING: "PET-EW",
      KEY_ACCOUNT_SPEC: "Billa Plus",
      PRICE: "0.94",
      PRODUCT_NAME: "Fanta Original Orange",
      BRAND: "Fanta",
    },
    {
      PACKAGING: "PET-EW",
      KEY_ACCOUNT_SPEC: "Eurogast C+C",
      PRICE: "0.79",
      PRODUCT_NAME: "Coca-Cola Original",
      BRAND: "Coca-Cola",
    },
    {
      PACKAGING: "PET-EW",
      KEY_ACCOUNT_SPEC: "Eurogast C+C",
      PRICE: "0.85",
      PRODUCT_NAME: "Coca-Cola Original",
      BRAND: "Coca-Cola",
    },
    {
      PACKAGING: "PET-EW",
      KEY_ACCOUNT_SPEC: "Eurogast C+C",
      PRICE: "0.95",
      PRODUCT_NAME: "Coca-Cola Original",
      BRAND: "Coca-Cola",
    },
    {
      PACKAGING: "PET-EW",
      KEY_ACCOUNT_SPEC: "Eurogast C+C",
      PRICE: "0.59",
      PRODUCT_NAME: "Coca-Cola Light",
      BRAND: "Coca-Cola Light",
    },
    {
      PACKAGING: "PET-EW",
      KEY_ACCOUNT_SPEC: "Eurogast C+C",
      PRICE: "0.79",
      PRODUCT_NAME: "Coca-Cola Light",
      BRAND: "Coca-Cola Light",
    },
    {
      PACKAGING: "PET-EW",
      KEY_ACCOUNT_SPEC: "Eurogast C+C",
      PRICE: "0.85",
      PRODUCT_NAME: "Coca-Cola Light",
      BRAND: "Coca-Cola Light",
    },
    {
      PACKAGING: "Dose EW",
      KEY_ACCOUNT_SPEC: "Eurogast C+C",
      PRICE: "0.59",
      PRODUCT_NAME: "Coca-Cola Zero",
      BRAND: "Coca-Cola Zero",
    },
    {
      PACKAGING: "PET-EW",
      KEY_ACCOUNT_SPEC: "Eurogast C+C",
      PRICE: "0.59",
      PRODUCT_NAME: "Coca-Cola Zero",
      BRAND: "Coca-Cola Zero",
    },
    {
      PACKAGING: "PET-EW",
      KEY_ACCOUNT_SPEC: "Eurogast C+C",
      PRICE: "0.59",
      PRODUCT_NAME: "Coca-Cola Zero Lemon",
      BRAND: "Coca-Cola Zero",
    },
    {
      PACKAGING: "PET-EW",
      KEY_ACCOUNT_SPEC: "Eurogast C+C",
      PRICE: "0.79",
      PRODUCT_NAME: "Fanta Original Orange",
      BRAND: "Fanta",
    },
    {
      PACKAGING: "PET-EW",
      KEY_ACCOUNT_SPEC: "Eurogast C+C",
      PRICE: "0.85",
      PRODUCT_NAME: "Fanta Original Orange",
      BRAND: "Fanta",
    },
    {
      PACKAGING: "PET-EW",
      KEY_ACCOUNT_SPEC: "Eurogast C+C",
      PRICE: "0.95",
      PRODUCT_NAME: "Fanta Original Orange",
      BRAND: "Fanta",
    },
    {
      PACKAGING: "PET-EW",
      KEY_ACCOUNT_SPEC: "Eurospar",
      PRICE: "1.59",
      PRODUCT_NAME: "Coca-Cola div. Sorten",
      BRAND: "Coca-Cola",
    },
    {
      PACKAGING: "PET-EW",
      KEY_ACCOUNT_SPEC: "Eurospar",
      PRICE: "1.26",
      PRODUCT_NAME: "Coca-Cola Original",
      BRAND: "Coca-Cola",
    },
    {
      PACKAGING: "PET-EW",
      KEY_ACCOUNT_SPEC: "Eurospar",
      PRICE: "1.59",
      PRODUCT_NAME: "Coca-Cola Original",
      BRAND: "Coca-Cola",
    },
    {
      PACKAGING: "PET-EW",
      KEY_ACCOUNT_SPEC: "Eurospar",
      PRICE: "1.26",
      PRODUCT_NAME: "Coca-Cola Light",
      BRAND: "Coca-Cola Light",
    },
    {
      PACKAGING: "PET-EW",
      KEY_ACCOUNT_SPEC: "Eurospar",
      PRICE: "1.26",
      PRODUCT_NAME: "Coca-Cola Zero",
      BRAND: "Coca-Cola Zero",
    },
    {
      PACKAGING: "PET-EW",
      KEY_ACCOUNT_SPEC: "Eurospar",
      PRICE: "1.26",
      PRODUCT_NAME: "Coca-Cola Zero Lemon",
      BRAND: "Coca-Cola Zero",
    },
    {
      PACKAGING: "PET-EW",
      KEY_ACCOUNT_SPEC: "Eurospar",
      PRICE: "1.26",
      PRODUCT_NAME: "Fanta Original Orange",
      BRAND: "Fanta",
    },
    {
      PACKAGING: "PET-EW",
      KEY_ACCOUNT_SPEC: "Eurospar",
      PRICE: "1.59",
      PRODUCT_NAME: "Fanta Original Orange",
      BRAND: "Fanta",
    },
    {
      PACKAGING: "PET-EW",
      KEY_ACCOUNT_SPEC: "Eurospar",
      PRICE: "1.26",
      PRODUCT_NAME: "Fanta Lemon Zero",
      BRAND: "Fanta Zero",
    },
    {
      PACKAGING: "Dose EW",
      KEY_ACCOUNT_SPEC: "Hofer",
      PRICE: "2.97",
      PRODUCT_NAME: "Coca-Cola Original",
      BRAND: "Coca-Cola",
    },
    {
      PACKAGING: "PET-EW",
      KEY_ACCOUNT_SPEC: "Hofer",
      PRICE: "1.17",
      PRODUCT_NAME: "Coca-Cola Original",
      BRAND: "Coca-Cola",
    },
    {
      PACKAGING: "PET-EW",
      KEY_ACCOUNT_SPEC: "Hofer",
      PRICE: "1.17",
      PRODUCT_NAME: "Coca-Cola Light",
      BRAND: "Coca-Cola Light",
    },
    {
      PACKAGING: "Dose EW",
      KEY_ACCOUNT_SPEC: "Hofer",
      PRICE: "2.97",
      PRODUCT_NAME: "Coca-Cola Zero",
      BRAND: "Coca-Cola Zero",
    },
    {
      PACKAGING: "PET-EW",
      KEY_ACCOUNT_SPEC: "Hofer",
      PRICE: "1.17",
      PRODUCT_NAME: "Coca-Cola Zero",
      BRAND: "Coca-Cola Zero",
    },
    {
      PACKAGING: "Dose EW",
      KEY_ACCOUNT_SPEC: "Hofer",
      PRICE: "2.97",
      PRODUCT_NAME: "Fanta Original Orange",
      BRAND: "Fanta",
    },
    {
      PACKAGING: "PET-EW",
      KEY_ACCOUNT_SPEC: "Hofer",
      PRICE: "1.17",
      PRODUCT_NAME: "Fanta Original Orange",
      BRAND: "Fanta",
    },
    {
      PACKAGING: "PET-EW",
      KEY_ACCOUNT_SPEC: "Interspar",
      PRICE: "1.59",
      PRODUCT_NAME: "Coca-Cola div. Sorten",
      BRAND: "Coca-Cola",
    },
    {
      PACKAGING: "PET-EW",
      KEY_ACCOUNT_SPEC: "Interspar",
      PRICE: "1.26",
      PRODUCT_NAME: "Coca-Cola Original",
      BRAND: "Coca-Cola",
    },
    {
      PACKAGING: "PET-EW",
      KEY_ACCOUNT_SPEC: "Interspar",
      PRICE: "1.59",
      PRODUCT_NAME: "Coca-Cola Original",
      BRAND: "Coca-Cola",
    },
    {
      PACKAGING: "PET-EW",
      KEY_ACCOUNT_SPEC: "Interspar",
      PRICE: "1.26",
      PRODUCT_NAME: "Coca-Cola Light",
      BRAND: "Coca-Cola Light",
    },
    {
      PACKAGING: "PET-EW",
      KEY_ACCOUNT_SPEC: "Interspar",
      PRICE: "1.59",
      PRODUCT_NAME: "Coca-Cola Light",
      BRAND: "Coca-Cola Light",
    },
    {
      PACKAGING: "PET-EW",
      KEY_ACCOUNT_SPEC: "Interspar",
      PRICE: "1.26",
      PRODUCT_NAME: "Coca-Cola Zero",
      BRAND: "Coca-Cola Zero",
    },
    {
      PACKAGING: "PET-EW",
      KEY_ACCOUNT_SPEC: "Interspar",
      PRICE: "1.26",
      PRODUCT_NAME: "Coca-Cola Zero Lemon",
      BRAND: "Coca-Cola Zero",
    },
    {
      PACKAGING: "PET-EW",
      KEY_ACCOUNT_SPEC: "Interspar",
      PRICE: "1.26",
      PRODUCT_NAME: "Fanta Original Orange",
      BRAND: "Fanta",
    },
    {
      PACKAGING: "PET-EW",
      KEY_ACCOUNT_SPEC: "Interspar",
      PRICE: "1.59",
      PRODUCT_NAME: "Fanta Original Orange",
      BRAND: "Fanta",
    },
    {
      PACKAGING: "Glas-Flasche Mehrweg",
      KEY_ACCOUNT_SPEC: "Kastner C+C",
      PRICE: "0.55",
      PRODUCT_NAME: "Coca-Cola Original",
      BRAND: "Coca-Cola",
    },
    {
      PACKAGING: "PET-EW",
      KEY_ACCOUNT_SPEC: "Kastner C+C",
      PRICE: "0.79",
      PRODUCT_NAME: "Coca-Cola Original",
      BRAND: "Coca-Cola",
    },
    {
      PACKAGING: "Glas-Flasche Mehrweg",
      KEY_ACCOUNT_SPEC: "Kastner C+C",
      PRICE: "0.55",
      PRODUCT_NAME: "Coca-Cola Light",
      BRAND: "Coca-Cola Light",
    },
    {
      PACKAGING: "Glas-Flasche Mehrweg",
      KEY_ACCOUNT_SPEC: "Kastner C+C",
      PRICE: "0.55",
      PRODUCT_NAME: "Coca-Cola Zero",
      BRAND: "Coca-Cola Zero",
    },
    {
      PACKAGING: "Glas-Flasche Mehrweg",
      KEY_ACCOUNT_SPEC: "Kastner C+C",
      PRICE: "0.55",
      PRODUCT_NAME: "Fanta Original Orange",
      BRAND: "Fanta",
    },
    {
      PACKAGING: "PET-EW",
      KEY_ACCOUNT_SPEC: "Kastner C+C",
      PRICE: "0.79",
      PRODUCT_NAME: "Fanta Original Orange",
      BRAND: "Fanta",
    },
    {
      PACKAGING: "Dose EW",
      KEY_ACCOUNT_SPEC: "KHG Gruppe",
      PRICE: "0.59",
      PRODUCT_NAME: "Coca-Cola Original",
      BRAND: "Coca-Cola",
    },
    {
      PACKAGING: "Dose EW",
      KEY_ACCOUNT_SPEC: "KHG Gruppe",
      PRICE: "0.65",
      PRODUCT_NAME: "Coca-Cola Original",
      BRAND: "Coca-Cola",
    },
    {
      PACKAGING: "PET-EW",
      KEY_ACCOUNT_SPEC: "KHG Gruppe",
      PRICE: "0.79",
      PRODUCT_NAME: "Coca-Cola Light",
      BRAND: "Coca-Cola Light",
    },
    {
      PACKAGING: "Dose EW",
      KEY_ACCOUNT_SPEC: "KHG Gruppe",
      PRICE: "0.65",
      PRODUCT_NAME: "Fanta Original Orange",
      BRAND: "Fanta",
    },
    {
      PACKAGING: "PET-EW",
      KEY_ACCOUNT_SPEC: "KHG Gruppe",
      PRICE: "0.79",
      PRODUCT_NAME: "Fanta Original Orange",
      BRAND: "Fanta",
    },
    {
      PACKAGING: "PET-EW",
      KEY_ACCOUNT_SPEC: "Lidl",
      PRICE: "1.59",
      PRODUCT_NAME: "Coca-Cola Original",
      BRAND: "Coca-Cola",
    },
    {
      PACKAGING: "",
      KEY_ACCOUNT_SPEC: "Lidl",
      PRICE: "2.99",
      PRODUCT_NAME: "Coca Cola Tablett Metall",
      BRAND: "Coca-Cola Produkte",
    },
    {
      PACKAGING: "",
      KEY_ACCOUNT_SPEC: "Lidl",
      PRICE: "2.99",
      PRODUCT_NAME: "Coca Cola Vorratsdose Metall",
      BRAND: "Coca-Cola Produkte",
    },
    {
      PACKAGING: "PET-EW",
      KEY_ACCOUNT_SPEC: "Lidl",
      PRICE: "1.59",
      PRODUCT_NAME: "Coca-Cola Zero",
      BRAND: "Coca-Cola Zero",
    },
    {
      PACKAGING: "PET-EW",
      KEY_ACCOUNT_SPEC: "Lidl",
      PRICE: "1.59",
      PRODUCT_NAME: "Fanta Original Orange",
      BRAND: "Fanta",
    },
    {
      PACKAGING: "Dose EW",
      KEY_ACCOUNT_SPEC: "Maxi VM",
      PRICE: "0.59",
      PRODUCT_NAME: "Coca-Cola Original",
      BRAND: "Coca-Cola",
    },
    {
      PACKAGING: "PET-EW",
      KEY_ACCOUNT_SPEC: "Maxi VM",
      PRICE: "0.99",
      PRODUCT_NAME: "Coca-Cola Original",
      BRAND: "Coca-Cola",
    },
    {
      PACKAGING: "PET-EW",
      KEY_ACCOUNT_SPEC: "Maxi VM",
      PRICE: "1.26",
      PRODUCT_NAME: "Coca-Cola Original",
      BRAND: "Coca-Cola",
    },
    {
      PACKAGING: "PET-EW",
      KEY_ACCOUNT_SPEC: "Maxi VM",
      PRICE: "1.59",
      PRODUCT_NAME: "Coca-Cola Original",
      BRAND: "Coca-Cola",
    },
    {
      PACKAGING: "Dose EW",
      KEY_ACCOUNT_SPEC: "Maxi VM",
      PRICE: "0.59",
      PRODUCT_NAME: "Coca-Cola Light",
      BRAND: "Coca-Cola Light",
    },
    {
      PACKAGING: "PET-EW",
      KEY_ACCOUNT_SPEC: "Maxi VM",
      PRICE: "0.99",
      PRODUCT_NAME: "Coca-Cola Light",
      BRAND: "Coca-Cola Light",
    },
    {
      PACKAGING: "PET-EW",
      KEY_ACCOUNT_SPEC: "Maxi VM",
      PRICE: "1.26",
      PRODUCT_NAME: "Coca-Cola Light",
      BRAND: "Coca-Cola Light",
    },
    {
      PACKAGING: "PET-EW",
      KEY_ACCOUNT_SPEC: "Maxi VM",
      PRICE: "1.59",
      PRODUCT_NAME: "Coca-Cola Light",
      BRAND: "Coca-Cola Light",
    },
    {
      PACKAGING: "",
      KEY_ACCOUNT_SPEC: "Maxi VM",
      PRICE: "29.70",
      PRODUCT_NAME: "Coca-Cola Popcorn Maker Snp-10 Cc",
      BRAND: "Coca-Cola Produkte",
    },
    {
      PACKAGING: "Dose EW",
      KEY_ACCOUNT_SPEC: "Maxi VM",
      PRICE: "0.59",
      PRODUCT_NAME: "Coca-Cola Zero",
      BRAND: "Coca-Cola Zero",
    },
    {
      PACKAGING: "PET-EW",
      KEY_ACCOUNT_SPEC: "Maxi VM",
      PRICE: "0.99",
      PRODUCT_NAME: "Coca-Cola Zero",
      BRAND: "Coca-Cola Zero",
    },
    {
      PACKAGING: "PET-EW",
      KEY_ACCOUNT_SPEC: "Maxi VM",
      PRICE: "1.26",
      PRODUCT_NAME: "Coca-Cola Zero",
      BRAND: "Coca-Cola Zero",
    },
    {
      PACKAGING: "PET-EW",
      KEY_ACCOUNT_SPEC: "Maxi VM",
      PRICE: "1.59",
      PRODUCT_NAME: "Coca-Cola Zero",
      BRAND: "Coca-Cola Zero",
    },
    {
      PACKAGING: "PET-EW",
      KEY_ACCOUNT_SPEC: "Maxi VM",
      PRICE: "0.99",
      PRODUCT_NAME: "Coca-Cola Zero Lemon",
      BRAND: "Coca-Cola Zero",
    },
    {
      PACKAGING: "PET-EW",
      KEY_ACCOUNT_SPEC: "Maxi VM",
      PRICE: "1.26",
      PRODUCT_NAME: "Coca-Cola Zero Lemon",
      BRAND: "Coca-Cola Zero",
    },
    {
      PACKAGING: "Dose EW",
      KEY_ACCOUNT_SPEC: "Maxi VM",
      PRICE: "0.59",
      PRODUCT_NAME: "Fanta Original Orange",
      BRAND: "Fanta",
    },
    {
      PACKAGING: "PET-EW",
      KEY_ACCOUNT_SPEC: "Maxi VM",
      PRICE: "0.99",
      PRODUCT_NAME: "Fanta Original Orange",
      BRAND: "Fanta",
    },
    {
      PACKAGING: "PET-EW",
      KEY_ACCOUNT_SPEC: "Maxi VM",
      PRICE: "1.26",
      PRODUCT_NAME: "Fanta Original Orange",
      BRAND: "Fanta",
    },
    {
      PACKAGING: "PET-EW",
      KEY_ACCOUNT_SPEC: "Maxi VM",
      PRICE: "1.59",
      PRODUCT_NAME: "Fanta Original Orange",
      BRAND: "Fanta",
    },
    {
      PACKAGING: "Dose EW",
      KEY_ACCOUNT_SPEC: "Metro C&C",
      PRICE: "0.46",
      PRODUCT_NAME: "Coca-Cola Original",
      BRAND: "Coca-Cola",
    },
    {
      PACKAGING: "PET-EW",
      KEY_ACCOUNT_SPEC: "Metro C&C",
      PRICE: "0.70",
      PRODUCT_NAME: "Coca-Cola Original",
      BRAND: "Coca-Cola",
    },
    {
      PACKAGING: "PET-EW",
      KEY_ACCOUNT_SPEC: "Metro C&C",
      PRICE: "1.19",
      PRODUCT_NAME: "Coca-Cola Original",
      BRAND: "Coca-Cola",
    },
    {
      PACKAGING: "PET-EW",
      KEY_ACCOUNT_SPEC: "Metro C&C",
      PRICE: "1.39",
      PRODUCT_NAME: "Coca-Cola Original",
      BRAND: "Coca-Cola",
    },
    {
      PACKAGING: "PET-EW",
      KEY_ACCOUNT_SPEC: "Metro C&C",
      PRICE: "0.70",
      PRODUCT_NAME: "Coca-Cola Zero",
      BRAND: "Coca-Cola Zero",
    },
    {
      PACKAGING: "PET-EW",
      KEY_ACCOUNT_SPEC: "Metro C&C",
      PRICE: "1.19",
      PRODUCT_NAME: "Coca-Cola Zero",
      BRAND: "Coca-Cola Zero",
    },
    {
      PACKAGING: "Dose EW",
      KEY_ACCOUNT_SPEC: "Metro C&C",
      PRICE: "0.46",
      PRODUCT_NAME: "Fanta div. Sorten",
      BRAND: "Fanta",
    },
    {
      PACKAGING: "PET-EW",
      KEY_ACCOUNT_SPEC: "Metro C&C",
      PRICE: "0.70",
      PRODUCT_NAME: "Fanta div. Sorten",
      BRAND: "Fanta",
    },
    {
      PACKAGING: "PET-EW",
      KEY_ACCOUNT_SPEC: "Metro C&C",
      PRICE: "1.19",
      PRODUCT_NAME: "Fanta div. Sorten",
      BRAND: "Fanta",
    },
    {
      PACKAGING: "PET-EW",
      KEY_ACCOUNT_SPEC: "Metro C&C",
      PRICE: "0.70",
      PRODUCT_NAME: "Fanta Original Orange",
      BRAND: "Fanta",
    },
    {
      PACKAGING: "PET-EW",
      KEY_ACCOUNT_SPEC: "Metro C&C",
      PRICE: "1.39",
      PRODUCT_NAME: "Fanta Original Orange",
      BRAND: "Fanta",
    },
    {
      PACKAGING: "Dose EW",
      KEY_ACCOUNT_SPEC: "M-Preis",
      PRICE: "1.39",
      PRODUCT_NAME: "Coca-Cola Original",
      BRAND: "Coca-Cola",
    },
    {
      PACKAGING: "Glas-Flasche Mehrweg",
      KEY_ACCOUNT_SPEC: "M-Preis",
      PRICE: "1.69",
      PRODUCT_NAME: "Coca-Cola Original",
      BRAND: "Coca-Cola",
    },
    {
      PACKAGING: "Dose EW",
      KEY_ACCOUNT_SPEC: "Nah & Frisch",
      PRICE: "0.89",
      PRODUCT_NAME: "Coca-Cola Original",
      BRAND: "Coca-Cola",
    },
    {
      PACKAGING: "Glas-Flasche Mehrweg",
      KEY_ACCOUNT_SPEC: "Nah & Frisch",
      PRICE: "0.69",
      PRODUCT_NAME: "Coca-Cola Original",
      BRAND: "Coca-Cola",
    },
    {
      PACKAGING: "Glas-Flasche Mehrweg",
      KEY_ACCOUNT_SPEC: "Nah & Frisch",
      PRICE: "1.59",
      PRODUCT_NAME: "Coca-Cola Original",
      BRAND: "Coca-Cola",
    },
    {
      PACKAGING: "PET-EW",
      KEY_ACCOUNT_SPEC: "Nah & Frisch",
      PRICE: "1.49",
      PRODUCT_NAME: "Coca-Cola Original",
      BRAND: "Coca-Cola",
    },
    {
      PACKAGING: "PET-EW",
      KEY_ACCOUNT_SPEC: "Nah & Frisch",
      PRICE: "1.89",
      PRODUCT_NAME: "Coca-Cola Original",
      BRAND: "Coca-Cola",
    },
    {
      PACKAGING: "Dose EW",
      KEY_ACCOUNT_SPEC: "Nah & Frisch",
      PRICE: "0.89",
      PRODUCT_NAME: "Coca-Cola Zero",
      BRAND: "Coca-Cola Zero",
    },
    {
      PACKAGING: "Glas-Flasche Mehrweg",
      KEY_ACCOUNT_SPEC: "Nah & Frisch",
      PRICE: "1.59",
      PRODUCT_NAME: "Coca-Cola Zero",
      BRAND: "Coca-Cola Zero",
    },
    {
      PACKAGING: "PET-EW",
      KEY_ACCOUNT_SPEC: "Nah & Frisch",
      PRICE: "1.49",
      PRODUCT_NAME: "Fanta div. Sorten",
      BRAND: "Fanta",
    },
    {
      PACKAGING: "Dose EW",
      KEY_ACCOUNT_SPEC: "Nah & Frisch",
      PRICE: "0.89",
      PRODUCT_NAME: "Fanta Original Orange",
      BRAND: "Fanta",
    },
    {
      PACKAGING: "Glas-Flasche Mehrweg",
      KEY_ACCOUNT_SPEC: "Nah & Frisch",
      PRICE: "0.69",
      PRODUCT_NAME: "Fanta Original Orange",
      BRAND: "Fanta",
    },
    {
      PACKAGING: "PET-EW",
      KEY_ACCOUNT_SPEC: "Nah & Frisch",
      PRICE: "1.89",
      PRODUCT_NAME: "Fanta Original Orange",
      BRAND: "Fanta",
    },
    {
      PACKAGING: "PET-EW",
      KEY_ACCOUNT_SPEC: "Penny Markt",
      PRICE: "2.09",
      PRODUCT_NAME: "Coca-Cola div. Sorten",
      BRAND: "Coca-Cola",
    },
    {
      PACKAGING: "Dose EW",
      KEY_ACCOUNT_SPEC: "Penny Markt",
      PRICE: "0.79",
      PRODUCT_NAME: "Coca-Cola Original",
      BRAND: "Coca-Cola",
    },
    {
      PACKAGING: "PET-EW",
      KEY_ACCOUNT_SPEC: "Penny Markt",
      PRICE: "1.49",
      PRODUCT_NAME: "Coca-Cola Original",
      BRAND: "Coca-Cola",
    },
    {
      PACKAGING: "PET-EW",
      KEY_ACCOUNT_SPEC: "Penny Markt",
      PRICE: "1.49",
      PRODUCT_NAME: "Coca-Cola Zero",
      BRAND: "Coca-Cola Zero",
    },
    {
      PACKAGING: "PET-EW",
      KEY_ACCOUNT_SPEC: "Penny Markt",
      PRICE: "2.09",
      PRODUCT_NAME: "Fanta div. Sorten",
      BRAND: "Fanta",
    },
    {
      PACKAGING: "Dose EW",
      KEY_ACCOUNT_SPEC: "Raiffeisen Verband Salzburg",
      PRICE: "0.62",
      PRODUCT_NAME: "Coca-Cola Original",
      BRAND: "Coca-Cola",
    },
    {
      PACKAGING: "PET-EW",
      KEY_ACCOUNT_SPEC: "Raiffeisen Verband Salzburg",
      PRICE: "1.49",
      PRODUCT_NAME: "Coca-Cola Original",
      BRAND: "Coca-Cola",
    },
    {
      PACKAGING: "PET-EW",
      KEY_ACCOUNT_SPEC: "Raiffeisen Verband Salzburg",
      PRICE: "1.49",
      PRODUCT_NAME: "Fanta Original Orange",
      BRAND: "Fanta",
    },
    {
      PACKAGING: "PET-EW",
      KEY_ACCOUNT_SPEC: "Riedhart",
      PRICE: "1.39",
      PRODUCT_NAME: "Coca-Cola Light",
      BRAND: "Coca-Cola Light",
    },
    {
      PACKAGING: "PET-EW",
      KEY_ACCOUNT_SPEC: "Spar",
      PRICE: "1.59",
      PRODUCT_NAME: "Coca-Cola div. Sorten",
      BRAND: "Coca-Cola",
    },
    {
      PACKAGING: "Dose EW",
      KEY_ACCOUNT_SPEC: "Spar",
      PRICE: "",
      PRODUCT_NAME: "Coca-Cola Original",
      BRAND: "Coca-Cola",
    },
    {
      PACKAGING: "PET-EW",
      KEY_ACCOUNT_SPEC: "Spar",
      PRICE: "",
      PRODUCT_NAME: "Coca-Cola Original",
      BRAND: "Coca-Cola",
    },
    {
      PACKAGING: "PET-EW",
      KEY_ACCOUNT_SPEC: "Spar",
      PRICE: "1.26",
      PRODUCT_NAME: "Coca-Cola Original",
      BRAND: "Coca-Cola",
    },
    {
      PACKAGING: "PET-EW",
      KEY_ACCOUNT_SPEC: "Spar",
      PRICE: "1.59",
      PRODUCT_NAME: "Coca-Cola Original",
      BRAND: "Coca-Cola",
    },
    {
      PACKAGING: "Dose EW",
      KEY_ACCOUNT_SPEC: "Spar",
      PRICE: "",
      PRODUCT_NAME: "Coca-Cola Vanilla",
      BRAND: "Coca-Cola",
    },
    {
      PACKAGING: "Dose EW",
      KEY_ACCOUNT_SPEC: "Spar",
      PRICE: "",
      PRODUCT_NAME: "Coca-Cola Light",
      BRAND: "Coca-Cola Light",
    },
    {
      PACKAGING: "PET-EW",
      KEY_ACCOUNT_SPEC: "Spar",
      PRICE: "",
      PRODUCT_NAME: "Coca-Cola Light",
      BRAND: "Coca-Cola Light",
    },
    {
      PACKAGING: "PET-EW",
      KEY_ACCOUNT_SPEC: "Spar",
      PRICE: "1.26",
      PRODUCT_NAME: "Coca-Cola Light",
      BRAND: "Coca-Cola Light",
    },
    {
      PACKAGING: "Dose EW",
      KEY_ACCOUNT_SPEC: "Spar",
      PRICE: "",
      PRODUCT_NAME: "Coca-Cola Zero",
      BRAND: "Coca-Cola Zero",
    },
    {
      PACKAGING: "PET-EW",
      KEY_ACCOUNT_SPEC: "Spar",
      PRICE: "",
      PRODUCT_NAME: "Coca-Cola Zero",
      BRAND: "Coca-Cola Zero",
    },
    {
      PACKAGING: "PET-EW",
      KEY_ACCOUNT_SPEC: "Spar",
      PRICE: "1.26",
      PRODUCT_NAME: "Coca-Cola Zero",
      BRAND: "Coca-Cola Zero",
    },
    {
      PACKAGING: "PET-EW",
      KEY_ACCOUNT_SPEC: "Spar",
      PRICE: "1.26",
      PRODUCT_NAME: "Coca-Cola Zero Lemon",
      BRAND: "Coca-Cola Zero",
    },
    {
      PACKAGING: "PET-EW",
      KEY_ACCOUNT_SPEC: "Spar",
      PRICE: "",
      PRODUCT_NAME: "Fanta Mango",
      BRAND: "Fanta",
    },
    {
      PACKAGING: "Dose EW",
      KEY_ACCOUNT_SPEC: "Spar",
      PRICE: "",
      PRODUCT_NAME: "Fanta Original Orange",
      BRAND: "Fanta",
    },
    {
      PACKAGING: "PET-EW",
      KEY_ACCOUNT_SPEC: "Spar",
      PRICE: "",
      PRODUCT_NAME: "Fanta Original Orange",
      BRAND: "Fanta",
    },
    {
      PACKAGING: "PET-EW",
      KEY_ACCOUNT_SPEC: "Spar",
      PRICE: "1.26",
      PRODUCT_NAME: "Fanta Original Orange",
      BRAND: "Fanta",
    },
    {
      PACKAGING: "PET-EW",
      KEY_ACCOUNT_SPEC: "Spar",
      PRICE: "1.59",
      PRODUCT_NAME: "Fanta Original Orange",
      BRAND: "Fanta",
    },
    {
      PACKAGING: "PET-EW",
      KEY_ACCOUNT_SPEC: "Spar",
      PRICE: "",
      PRODUCT_NAME: "Fanta Lemon Zero",
      BRAND: "Fanta Zero",
    },
    {
      PACKAGING: "PET-EW",
      KEY_ACCOUNT_SPEC: "Spar",
      PRICE: "1.26",
      PRODUCT_NAME: "Fanta Lemon Zero",
      BRAND: "Fanta Zero",
    },
    {
      PACKAGING: "PET-EW",
      KEY_ACCOUNT_SPEC: "Sutterlüty-Rewe",
      PRICE: "1.29",
      PRODUCT_NAME: "Coca-Cola Original",
      BRAND: "Coca-Cola",
    },
    {
      PACKAGING: "PET-EW",
      KEY_ACCOUNT_SPEC: "Sutterlüty-Rewe",
      PRICE: "1.29",
      PRODUCT_NAME: "Fanta Original Orange",
      BRAND: "Fanta",
    },
    {
      PACKAGING: "PET-EW",
      KEY_ACCOUNT_SPEC: "T&G Tiefkühl & Getränkemarkt",
      PRICE: "1.69",
      PRODUCT_NAME: "Coca-Cola Original",
      BRAND: "Coca-Cola",
    },
    {
      PACKAGING: "PET-EW",
      KEY_ACCOUNT_SPEC: "T&G Tiefkühl & Getränkemarkt",
      PRICE: "1.69",
      PRODUCT_NAME: "Coca-Cola Zero",
      BRAND: "Coca-Cola Zero",
    },
    {
      PACKAGING: "PET-EW",
      KEY_ACCOUNT_SPEC: "T&G Tiefkühl & Getränkemarkt",
      PRICE: "1.69",
      PRODUCT_NAME: "Fanta Original Orange",
      BRAND: "Fanta",
    },
    {
      PACKAGING: "PET-EW",
      KEY_ACCOUNT_SPEC: "Transgourmet",
      PRICE: "0.70",
      PRODUCT_NAME: "Coca-Cola Zero",
      BRAND: "Coca-Cola Zero",
    },
    {
      PACKAGING: "PET-EW",
      KEY_ACCOUNT_SPEC: "Transgourmet",
      PRICE: "1.35",
      PRODUCT_NAME: "Coca-Cola Zero",
      BRAND: "Coca-Cola Zero",
    },
    {
      PACKAGING: "PET-EW",
      KEY_ACCOUNT_SPEC: "Transgourmet",
      PRICE: "0.70",
      PRODUCT_NAME: "Fanta Original Orange",
      BRAND: "Fanta",
    },
    {
      PACKAGING: "PET-EW",
      KEY_ACCOUNT_SPEC: "Transgourmet",
      PRICE: "1.35",
      PRODUCT_NAME: "Fanta Original Orange",
      BRAND: "Fanta",
    },
    {
      PACKAGING: "PET-EW",
      KEY_ACCOUNT_SPEC: "Unimarkt",
      PRICE: "1.26",
      PRODUCT_NAME: "Coca-Cola Original",
      BRAND: "Coca-Cola",
    },
    {
      PACKAGING: "PET-EW",
      KEY_ACCOUNT_SPEC: "Unimarkt",
      PRICE: "1.99",
      PRODUCT_NAME: "Coca-Cola Original",
      BRAND: "Coca-Cola",
    },
    {
      PACKAGING: "PET-EW",
      KEY_ACCOUNT_SPEC: "Unimarkt",
      PRICE: "1.52",
      PRODUCT_NAME: "Coca-Cola Light",
      BRAND: "Coca-Cola Light",
    },
    {
      PACKAGING: "PET-EW",
      KEY_ACCOUNT_SPEC: "Unimarkt",
      PRICE: "1.26",
      PRODUCT_NAME: "Coca-Cola Zero",
      BRAND: "Coca-Cola Zero",
    },
    {
      PACKAGING: "PET-EW",
      KEY_ACCOUNT_SPEC: "Unimarkt",
      PRICE: "1.26",
      PRODUCT_NAME: "Fanta Original Orange",
      BRAND: "Fanta",
    },
    {
      PACKAGING: "PET-EW",
      KEY_ACCOUNT_SPEC: "Unimarkt",
      PRICE: "1.52",
      PRODUCT_NAME: "Fanta Original Orange",
      BRAND: "Fanta",
    },
    {
      PACKAGING: "PET-EW",
      KEY_ACCOUNT_SPEC: "Unimarkt",
      PRICE: "1.99",
      PRODUCT_NAME: "Fanta Original Orange",
      BRAND: "Fanta",
    },
    {
      PACKAGING: "PET-EW",
      KEY_ACCOUNT_SPEC: "WEDL C+C",
      PRICE: "1.35",
      PRODUCT_NAME: "Coca-Cola Original",
      BRAND: "Coca-Cola",
    },
    {
      PACKAGING: "PET-EW",
      KEY_ACCOUNT_SPEC: "WEDL C+C",
      PRICE: "1.65",
      PRODUCT_NAME: "Coca-Cola Original",
      BRAND: "Coca-Cola",
    },
    {
      PACKAGING: "PET-EW",
      KEY_ACCOUNT_SPEC: "WEDL C+C",
      PRICE: "1.35",
      PRODUCT_NAME: "Coca-Cola Light",
      BRAND: "Coca-Cola Light",
    },
    {
      PACKAGING: "PET-EW",
      KEY_ACCOUNT_SPEC: "WEDL C+C",
      PRICE: "1.65",
      PRODUCT_NAME: "Coca-Cola Light",
      BRAND: "Coca-Cola Light",
    },
    {
      PACKAGING: "PET-EW",
      KEY_ACCOUNT_SPEC: "WEDL C+C",
      PRICE: "1.35",
      PRODUCT_NAME: "Coca-Cola Zero",
      BRAND: "Coca-Cola Zero",
    },
    {
      PACKAGING: "PET-EW",
      KEY_ACCOUNT_SPEC: "WEDL C+C",
      PRICE: "1.35",
      PRODUCT_NAME: "Fanta Original Orange",
      BRAND: "Fanta",
    },
    {
      PACKAGING: "PET-EW",
      KEY_ACCOUNT_SPEC: "WEDL C+C",
      PRICE: "1.65",
      PRODUCT_NAME: "Fanta Original Orange",
      BRAND: "Fanta",
    },
    {
      PACKAGING: "PET-EW",
      KEY_ACCOUNT_SPEC: "Winkler Markt",
      PRICE: "0.99",
      PRODUCT_NAME: "Coca-Cola Original",
      BRAND: "Coca-Cola",
    },
    {
      PACKAGING: "PET-EW",
      KEY_ACCOUNT_SPEC: "Winkler Markt",
      PRICE: "0.99",
      PRODUCT_NAME: "Coca-Cola Zero",
      BRAND: "Coca-Cola Zero",
    },
  ],
  count: "181",
};

export default data;
